spring:
  application:
    name: usian-content-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
    host: 127.0.0.1
    port: 6379
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#大广告位图片信息
AD_CATEGORY_ID: 89
AD_HEIGHT: 240
AD_WIDTH: 670
AD_HEIGHTB: 240
AD_WIDTHB: 550
#配置缓存首页大广告位的 key
PORTAL_AD_KEY: PORTAL_AD_KEY