spring:
  application:
    name: usian-item-web
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/